# Generated by Django 5.2.17 on 2026-09-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo of medicine box or tablet for easy visual reference', null=True, upload_to='medicines/'),
        ),
    ]
